INSERT INTO `db_grupo2`.`usuario`
(   `nombre_de_usuario`,  `apellido`, `fecha_de_nacimiento`,       `nombre`, `password`) VALUES
(   'Antonino@González',  'González',       '2002-09-26',     'Antonino',   'I7A8G9'),
(   'Augusto@Rodríguez', 'Rodríguez',       '2006-06-12',      'Augusto',   'Q0V1H1'),
(     'Bonifacio@Gómez',     'Gómez',       '2002-01-27',    'Bonifacio',   'Z0R6S1'),
( 'Benedicto@Fernández', 'Fernández',       '2006-01-09',    'Benedicto',   'J1M8P5'),
(      'Clemente@López',     'López',       '2014-09-14',     'Clemente',   'K1J9U1'),
(       'Cipriano@Díaz',      'Díaz',       '2001-04-02',     'Cipriano',   'I7K3J1'),
(   'Dalmacio@Martínez',  'Martínez',       '2013-08-11',     'Dalmacio',   'F1S9X0'),
(       'Deodato@Pérez',     'Pérez',       '2006-03-27',      'Deodato',   'A2D2S2'),
(     'Emeterio@García',    'García',       '2001-05-29',     'Emeterio',   'O6G9E9'),
(       'Ennio@Sánchez',   'Sánchez',       '2010-05-28',        'Ennio',   'T3C9V3'),
(       'Fausto@Romero',    'Romero',       '2002-12-24',       'Fausto',   'B3X9E9'),
(      'Fulgencio@Sosa',      'Sosa',       '2002-07-30',    'Fulgencio',   'Z1K5N1'),
(       'Gabino@Torres',    'Torres',       '2003-07-13',       'Gabino',   'R1A6H3'),
(   'Gaudencio@Álvarez',   'Álvarez',       '2017-08-23',    'Gaudencio',   'A7K7S3'),
(        'Hilario@Ruiz',      'Ruiz',       '2015-07-03',      'Hilario',   'J9Y6N7'),
(    'Honorato@Ramírez',   'Ramírez',       '2010-04-10',     'Honorato',   'J4K3A0'),
(      'Ignacio@Flores',    'Flores',       '2005-04-01',      'Ignacio',   'S1P9G7'),
(         'Ivo@Benítez',   'Benítez',       '2019-07-28',          'Ivo',   'F8K0U5'),
(       'Jenaro@Acosta',    'Acosta',       '2003-11-22',       'Jenaro',   'A2F9Y3'),
(        'Julio@Medina',    'Medina',       '2003-06-15',        'Julio',   'A5W0N2'),
(    'Laureano@Herrera',   'Herrera',       '2002-07-18',     'Laureano',   'V3G9K2'),
(      'Lorenzo@Suárez',    'Suárez',       '2015-10-14',      'Lorenzo',   'L9Y8E6'),
(     'Mamerto@Aguirre',   'Aguirre',       '2017-12-28',      'Mamerto',   'L0U9D1'),
(      'Máximo@Giménez',   'Giménez',       '2017-12-12',       'Máximo',   'P5X3W1'),
(   'Nicanor@Gutiérrez', 'Gutiérrez',       '2003-11-12',      'Nicanor',   'O0K6H9'),
(    'Nazareno@Pereyra',   'Pereyra',       '2011-05-06',     'Nazareno',   'I6A6I4'),
(       'Octavio@Rojas',     'Rojas',       '2008-04-22',      'Octavio',   'H7D6I4'),
(         'Omar@Molina',    'Molina',       '2009-05-29',         'Omar',   'W0B3A2'),
(      'Pascual@Castro',    'Castro',       '2000-11-07',      'Pascual',   'I5N9K7'),
(     'Prudencio@Ortiz',     'Ortiz',       '2017-12-09',    'Prudencio',   'F8L4O3'),
(        'Renato@Silva',     'Silva',       '2001-01-07',       'Renato',   'U2L2J3'),
(         'Román@Núñez',     'Núñez',       '2007-06-13',        'Román',   'K1D9R1'),
(         'Sancho@Luna',      'Luna',       '2011-08-08',       'Sancho',   'E2L5Q7'),
(       'Severo@Juárez',    'Juárez',       '2012-12-29',       'Severo',   'P5Y4X6'),
(     'Toribio@Cabrera',   'Cabrera',       '2003-12-20',      'Toribio',   'L0K0C5'),
(       'Teodosio@Ríos',      'Ríos',       '2006-12-17',     'Teodosio',   'E3L0S6'),
(        'Urso@Morales',   'Morales',       '2002-10-04',         'Urso',   'M0S0L1'),
(        'Udolfo@Godoy',     'Godoy',       '2011-09-01',       'Udolfo',   'L9P3M2'),
(     'Valdemar@Moreno',    'Moreno',       '2019-06-19',     'Valdemar',   'V0H9K0'),
( 'Vespasiano@Ferreyra',  'Ferreyra',       '2017-09-13',   'Vespasiano',   'R1U0O1'),
( 'Wilfrido@Domínguez',  'domínguez',       '2011-11-24',     'Wilfrido',   'E9L7A7'),
(   'Wenceslao@Carrizo',   'Carrizo',       '2001-03-18',    'Wenceslao',   'X3X0B6'),
(      'Xavier@Peralta',   'Peralta',       '2010-03-10',       'Xavier',   'R3U9M5'),
(    'Xóchtil@Castillo',  'Castillo',       '2007-06-03',      'Xóchtil',   'E0X4O2'),
(        'Yune@Ledesma',   'Ledesma',       '2017-02-03',         'Yune',   'U3V2T9'),
(        'Yaco@Quiroga',   'Quiroga',       '2008-03-24',         'Yaco',   'D7K0G8'),
(          'Zenón@Vega',      'Vega',       '2018-11-27',        'Zenón',   'B4V5N1'),
(        'Zenobio@Vera',      'Vera',       '2018-10-31',      'Zenobio',   'G5W7V7'),
(         'Astor@Muñoz',     'Muñoz',       '2017-02-03',        'Astor',   'P3T3S6'),
(        'Amadeo@Ojeda',     'Ojeda',       '2007-02-22',       'Amadeo',   'N2Q5Q5'),
(          'Alba@Ponce',     'Ponce',       '2003-02-23',         'Alba',   'W1G6V1'),
(     'Amparo@Villalba',  'Villalba',       '2001-10-08',       'Amparo',   'I7U7Q2'),
(      'Aurora@Cardozo',   'Cardozo',       '2009-01-07',       'Aurora',   'B0M4R5'),
(     'Beatrix@Navarro',   'Navarro',       '2011-10-20',      'Beatrix',   'F1W1K2'),
(      'Benita@Coronel',   'Coronel',       '2007-12-18',       'Benita',   'U6C7N0'),
(     'Caridad@Vázquez',   'Vázquez',       '2013-07-05',      'Caridad',   'E0T9S3'),
(   'Consolación@Ramos',     'Ramos',       '2005-04-21',  'Consolación',   'T1J9B6'),
(    'Covadonga@Vargas',    'Vargas',       '2000-12-09',    'Covadonga',   'L4S0Q7'),
(       'Diana@Cáceres',   'Cáceres',       '2017-08-08',        'Diana',   'V7Q8O2'),
(       'Dolores@Arias',     'Arias',       '2004-10-16',      'Dolores',   'Y4D0Z2'),
('Encarnación@Figueroa',  'Figueroa',       '2019-06-07',  'Encarnación',   'H8T2D9'),
(    'Engracia@Córdoba',   'Córdoba',       '2004-05-06',     'Engracia',   'X2C9G5'),
(    'Esperanza@Correa',    'Correa',       '2019-05-10',    'Esperanza',   'K5A4R1'),
( 'Felicidad@Maldonado', 'Maldonado',       '2017-03-12',    'Felicidad',   'Y8G3H3'),
(           'Flora@Paz',       'Paz',       '2017-11-28',        'Flora',   'N9H7B4'),
(         'Gema@Rivero',    'Rivero',       '2008-08-01',         'Gema',   'K7W1V0'),
(      'Gloria@Miranda',   'Miranda',       '2002-10-13',       'Gloria',   'E6N1O6'),
(     'Gracia@Mansilla',  'Mansilla',       '2011-02-01',       'Gracia',   'F3Y7D8'),
(    'Hortensia@Farias',    'Farias',       '2017-04-26',    'Hortensia',   'W0Z8L8'),
(       'Imelda@Roldán',    'Roldán',       '2010-05-03',       'Imelda',   'B8G7I1'),
(       'Jovita@Méndez',    'Méndez',       '2017-10-15',       'Jovita',   'B7V8K2'),
(        'Julia@Guzmán',    'Guzmán',       '2001-01-02',        'Julia',   'E1A8G0'),
(      'Leticia@Aguero',    'Aguero',       '2016-08-30',      'Leticia',   'M4D0B3'),
(     'Lucía@Hernández', 'Hernández',       '2011-06-11',        'Lucía',   'I1I5N3'),
(          'Luz@Lucero',    'Lucero',       '2018-03-26',          'Luz',   'A8J5M3'),
(        'Mariana@Cruz',      'Cruz',       '2015-07-21',      'Mariana',   'K0U0V0'),
(         'Marina@Páez',      'Páez',       '2007-11-08',       'Marina',   'L8F1K9'),
(     'Nivaria@Escobar',   'Escobar',       '2017-12-04',      'Nivaria',   'M9O9K7'),
(      'Noelia@Mendoza',   'Mendoza',       '2006-10-28',       'Noelia',   'H5S5H4'),
(       'Norma@Barrios',   'Barrios',       '2000-01-26',        'Norma',   'W5C7N3'),
(       'Olivia@Bustos',    'Bustos',       '2014-08-25',       'Olivia',   'U1S6L1'),
(        'Paloma@Ávila',     'Ávila',       '2015-11-10',       'Paloma',   'C5I0Y4'),
(      'Patricio@Ayala',     'Ayala',       '2000-06-17',     'Patricio',   'Q5D1L6'),
(        'Petra@Blanco',    'Blanco',       '2010-06-22',        'Petra',   'Q1C3A9'),
(  'Purificación@Soria',     'Soria',       '2018-10-08', 'Purificación',   'M2P6D9'),
(       'Rocío@Maidana',   'Maidana',       '2015-02-24',        'Rocío',   'T6W1I0'),
(       'Rosalba@Acuña',     'Acuña',       '2015-08-26',      'Rosalba',   'Z8P6L1'),
(    'RupesNigra@Leiva',     'Leiva',       '2006-09-16',  'Rupes Nigra',   'I3K1B0'),
(       'Silvia@Duarte',    'Duarte',       '2006-02-01',       'Silvia',   'C8R8O2'),
(      'Taciana@Moyano',    'Moyano',       '2002-06-03',      'Taciana',   'A4U6Q0'),
(       'Ursula@Campos',    'Campos',       '2002-05-20',       'Ursula',   'U6A7W2'),
(      'Valentina@Soto',      'Soto',       '2002-09-03',    'Valentina',   'L0M1B1'),
(     'Verónica@Martín',    'Martín',       '2010-06-23',     'Verónica',   'X4L2M6'),
(     'Victoria@Valdez',    'Valdez',       '2004-10-02',     'Victoria',   'X1V9G3'),
(      'Virginia@Bravo',     'Bravo',       '2009-03-14',     'Virginia',   'G4J7D2'),
(     'Zeferina@Chávez',    'Chávez',       '2017-09-28',     'Zeferina',   'S0N7N5'),
(   'Claudis@Velázquez', 'Velázquez',       '2019-01-17',      'Claudis',   'U3D8U0'),
(     'Honoria@Olivera',   'Olivera',       '2006-02-24',      'Honoria',   'W7E9A9'),
(   'Clementina@Toledo',    'Toledo',       '2001-03-04',   'Clementina',   'L6R8S9'),
(          'Eva@Franco',    'Franco',       '2017-06-26',          'Eva',   'E4P3R2');

INSERT INTO `db_grupo2`.`categoria`
(`id_categoria`,              `descripcion`) VALUES
(           '1',             'arquitectura‎'),
(           '2',                  'ciencia‎'),
(           '3',                     'cine‎'),
(           '4',                 'deportes‎'),
(           '5',                'ganadería‎'),
(           '6',                 'historia‎'),
(           '7',                    'humor‎'),
(           '8',                 'infancia‎'),
(           '9',      'no ficción por tema‎'),
(          '10', 'derechos de los animales‎'),
(          '11',        'el transhumanismo‎'),
(          '12',                'la muerte'),
(          '13',                   'música‎'),
(          '14',                   'países'),
(          '15',                 'política‎'),
(          '16',                 'religión‎'),
(          '17',              'tauromaquia‎'),
(          '18',               'televisión‎'),
(          '19',                   'viajes‎'),
(          '20',      'vida extraterrestre');

INSERT INTO `db_grupo2`.`contenido`
(                                                                `titulo`,  `fecha_publicacion`, `extension_archivo`) VALUES
(                                                          'Don Quijote ',        '1605-01-01',             'epub'),
(                      'Historia de dos ciudades (A Tale of Two Cities) ',        '1859-01-01',              'doc'),
(                      'El Señor de los Anillos (The Lord of the Rings) ',        '1954-01-01',             'epub'),
(                                      'El principito (Le Petit Prince) ',        '1943-01-01',              'doc'),
(                                               'El hobbit (The Hobbit) ',        '1937-01-01',             'epub'),
(                            'Sueño en el pabellón rojo (Hóng lóu mèng) ',        '1759-01-01',              'pdf'),
(                             'Triple representatividad (Sānge dàibiǎo) ',        '2001-01-01',              'pdf'),
(                                                        'Diez negritos ',        '1939-01-01',             'epub'),
(                 'Las aventuras de Alicia en el país de las maravillas ',        '1865-01-01',              'doc'),
( 'El león, la bruja y el ropero (The Lion, the Witch and the Wardrobe) ',        '1950-01-01',             'epub'),
(                                                           'Ella (She) ',        '1887-01-01',              'doc'),
(                               'El código Da Vinci (The Da Vinci Code) ',        '2003-01-01',             'epub'),
(                           'El cazador oculto (The Catcher in the Rye) ',        '1951-01-01',              'pdf'),
(                                         'El alquimista (O Alquimista) ',        '1988-01-01',              'pdf'),
(                                 'El camino a Cristo (Steps to Christ) ',        '1892-01-01',              'doc'),
(                                 'Heidi (Heidis Lehr- und Wanderjahre) ',        '1880-01-01',              'doc'),
(                       'Ana de las Tejas Verdes (Anne of Green Gables) ',        '1908-01-01',              'doc'),
(                            'El nombre de la rosa (Il Nome della Rosa) ',        '1980-01-01',              'txt'),
(                                    'El informe Hite (The Hite Report) ',        '1976-01-01',              'txt'),
(                           'La telaraña de Charlotte (Charlotte´s Web) ',        '1952-01-01',              'txt'),
(   'El cuento de Perico, el conejo travieso (The Tale of Peter Rabbit) ',        '1902-01-01',              'txt'),
(                            'Harry Potter y las Reliquias de la Muerte' ,        '2007-01-01',              'txt'),
(                  'Juan Salvador Gaviota (Jonathan Livingston Seagull) ',        '1970-01-01',              'txt'),
(                            'Un mensaje a García (A Message to Garcia) ',        '1899-01-01',              'txt'),
(                               'Ángeles y demonios (Angels and Demons) ',        '2000-01-01',              'doc'),
( 'Así se templó el acero (Как закалялась сталь, Kak zakalyalas´ stal´) ',        '1932-01-01',              'pdf'),
(                              'Guerra y paz (Война и мир, Voyna i mir) ',        '1869-01-01',              'pdf'),
(                                             'Las aventuras de Pinocho ',        '1881-01-01',             'epub'),
(                   'Usted puede sanar su vida (You Can Heal Your Life) ',        '1984-01-01',              'txt'),
(                                          'Kane y Abel (Kane and Abel) ',        '1979-01-01',              'doc'),
(                            '50 sombras de Grey (Fifty Shades of Grey) ',        '2011-01-01',             'epub'),
(     'Diario de Ana Frank o Las habitaciones de atrás (Het Achterhuis) ',        '1947-01-01',              'pdf'),
(                    'En Sus pasos (In His Steps: What Would Jesus Do?) ',        '1896-01-01',              'pdf'),
(                            'Matar un ruiseñor (To Kill a Mockingbird) ',        '1960-01-01',             'epub'),
(                        'El valle de las muñecas (Valley of the Dolls) ',        '1966-01-01',              'pdf'),
(                       'Lo que el viento se llevó (Gone with the Wind) ',        '1936-01-01',              'doc'),
(                                                 'Cien años de soledad ',        '1967-01-01',              'txt'),
(                     'Una vida con propósito (The Purpose Driven Life) ',        '2002-01-01',              'doc'),
(    'El pájaro espino, El pájaro canta hasta morir o Amor entre espinas',        '1977-01-01',              'doc'),
(                           'Piense y hágase rico (Think and Grow Rich) ',        '1937-01-01',              'txt'),
(           'La rebeldía de la Sra. Stover (The Revolt of Mamie Stover) ',        '1951-01-01',             'epub'),
(      'Los hombres que no amaban a las mujeres (Män som hatar kvinnor) ',        '2005-01-01',              'doc'),
(               'La pequeña oruga glotona (The Very Hungry Caterpillar) ',        '1969-01-01',             'epub'),
(                         'El Diario de Greg (The Diary of a Wimpy Kid) ',        '2008-01-01',              'txt'),
(     'La agonía del gran planeta Tierra (The Late, Great Planet Earth) ',        '1970-01-01',              'txt'),
(         'Princesa mecánica (The Infernal Devices: Clockwork Princess) ',        '2013-01-01',             'epub'),
(                '¿Quién se ha llevado mi queso? (Who Moved My Cheese?) ',        '1998-01-01',             'epub'),
(                    'El viento en los sauces (The Wind in the Willows) ',        '1908-01-01',              'doc'),
(                                          '1984 (Nineteen Eighty-Four) ',        '1949-01-01',              'pdf'),
(                             'Los juegos del hambre (The Hunger Games) ',        '2008-01-01',             'epub'),
(                      'Las Nueve Revelaciones (The Celestine Prophecy) ',        '1993-01-01',              'txt'),
(                                           'El Padrino (The Godfather) ',        '1969-01-01',              'doc'),
(                                                           'Love Story ',        '1970-01-01',             'epub'),
(                                             'Tótem Lobo (Láng Túténg) ',        '2004-01-01',              'pdf'),
(                 'La prostituta feliz (The Happy Hooker: My Own Story) ',        '1971-01-01',             'epub'),
(                                                       'Tiburón (Jaws) ',        '1974-01-01',              'txt'),
(                                 'Siempre te querré (Love You Forever) ',        '1986-01-01',              'pdf'),
(                                    'El mundo de Sofía (Sofies verden) ',        '1991-01-01',              'txt'),
(          'Sólo para mujeres, o simplemente Mujeres (The Women´s Room) ',        '1977-01-01',              'pdf'),
(                                 'Qué esperar cuando se está esperando ',        '1984-01-01',              'pdf'),
(                                   'Diario de Greg : La Ley de Rodrick ',        '2010-01-01',              'doc'),
(                                           'Ciudad del Fuego Celestial ',        '2014-01-01',             'epub'),
(                'Donde viven los monstruos (Where The Wild Things Are) ',        '1963-01-01',              'doc'),
(                                              'El secreto (The Secret) ',        '2006-01-01',              'doc'),
(                                       'Miedo a volar (Fear of Flying) ',        '1973-01-01',              'pdf'),
(                                 'Buenas noches, Luna (Goodnight Moon) ',        '1947-01-01',              'doc'),
(                 'Adivina cuánto te quiero (Guess How Much I Love You) ',        '1994-01-01',              'doc'),
(                'Los siete hábitos de las personas altamente efectivas ',        '1989-01-01',              'doc'),
(                                                               'Shōgun ',        '1975-01-01',              'doc'),
(                      'El pequeño perrito Poky (The Poky Little Puppy) ',        '1942-01-01',              'doc'),
(                  'Los pilares de la Tierra (The Pillars of the Earth) ',        '1989-01-01',              'txt'),
(                       'Cómo ganar amigos e influir sobre las personas ',        '1936-01-01',              'doc'),
(                      'El perfume o El perfume: historia de un asesino ',        '1985-01-01',              'doc'),
(                      'El hombre que susurraba al oído de los caballos ',        '1995-01-01',             'epub'),
(                                                 'La sombra del viento ',        '2001-01-01',              'pdf'),
(                                                'La cabaña (The Shack) ',        '2007-01-01',              'pdf'),
(                                            'En llamas (Catching Fire) ',        '2009-01-01',              'pdf'),
(        'Guía del autoestopista galáctico o Guía del viajero galáctico ',        '1979-01-01',              'doc'),
(                  'Martes con mi viejo profesor (Tuesdays with Morrie) ',        '1997-01-01',              'pdf'),
(                               'La parcela de Dios (God´s Little Acre) ',        '1933-01-01',              'txt'),
(               'Donde el corazón te lleve (Va´ dove ti porta il cuore) ',        '1994-01-01',              'txt'),
(                                                 'Sinsajo (Mockingjay) ',        '2010-01-01',              'doc'),
(                                             'Rebeldes (The Outsiders) ',        '1967-01-01',              'pdf'),
(                                    'Charlie y la fábrica de chocolate ',        '1964-01-01',              'doc'),
(                                        'Tokio blues (Noruwei no Mori) ',        '1987-01-01',             'epub'),
(                                                         'Peyton Place ',        '1956-01-01',             'epub'),
(                                                                 'Dune ',        '1965-01-01',              'doc'),
(                                                  'La peste (La Peste) ',        '1947-01-01',              'pdf'),
(                              'Indigno de ser humano (Ningen shikkaku) ',        '1948-01-01',             'epub'),
(                                      'El mono desnudo (The Naked Ape) ',        '1968-01-01',             'epub'),
(               'Los puentes de Madison (The Bridges of Madison County) ',        '1992-01-01',              'pdf'),
(                                'Todo se desmorona (Things Fall Apart) ',        '1958-01-01',             'epub'),
(                                             'El profeta (The Prophet) ',        '1923-01-01',              'doc'),
(                                          'El exorcista (The Exorcist) ',        '1971-01-01',              'pdf'),
(                                            'El grúfalo (The Gruffalo) ',        '1999-01-01',              'pdf'),
(                                                 'Trampa 22 (Catch-22) ',        '1961-01-01',              'doc'),
(          'La isla de las tormentas (Storm Island o Eye of the Needle) ',        '1978-01-01',             'epub'),
(                                                     'El gato garabato ',        '1957-01-01',              'doc'),
(                                    'Desde mi cielo (The Lovely Bones) ',        '2002-01-01',              'doc'),
(                                         'Cisnes salvajes (Wild Swans) ',        '1992-01-01',              'doc'),
(                                                          'Santa Evita ',        '1995-01-01',             'epub'),
(                                   'La noche (Un di Velt Hot Geshvign) ',        '1958-01-01',             'epub'),
(                                'Cometas en el cielo (The Kite Runner) ',        '2003-01-01',             'epub'),
(              'Observaciones de Yu Dan sobre las Analectas de Confucio ',        '2006-01-01',              'doc'),
(                                     'La mujer total (The Total Woman) ',        '1974-01-01',              'doc'),
(                    'Historia del futuro, la sociedad del conocimiento ',        '1985-01-01',              'txt'),
(                         'Problemas de la economía socialista de China ',        '1979-01-01',              'pdf'),
(      '¿De qué color es su paracaídas? (What Color is Your Parachute?) ',        '1970-01-01',              'doc');

INSERT INTO `db_grupo2`.`documento` SELECT `id_contenido` FROM `db_grupo2`.`contenido`;

-- #####################################################################################################################
-- TIGGERS
-- #####################################################################################################################
use db_grupo2;
create trigger tgr_documentos after insert on `db_grupo2`.`contenido` for each row  insert into `db_grupo2`.`documento` (`id_contenido`) values (NEW.`id_contenido`);
create trigger tgr_musica after insert on `db_grupo2`.`contenido` for each row  insert into `db_grupo2`.`musica` (`id_contenido`) values (NEW.`id_contenido`);

